Edit advisor
WildCodeSchool/lille_0919_PHP_ma_gouvernance pull request #40
Opened 2020-01-23 14:47 UTC by RMayeux

2020-01-23 15:22 UTC, clemcx approved these changes

2020-01-23 15:57 UTC, benj-san requested changes

2020-01-23 15:57 UTC, benj-san commented on templates/cvAdvisor.html.twig
> +                    {% if commentary is defined %}
Can't you find a better solution than a plain word for event triggering

2020-01-26 12:13 UTC, benj-san approved these changes

2020-01-26 12:14 UTC, benj-san reviewed
Resolve conflicts before merge

2020-01-27 08:35 UTC, merged